version: 2


jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
        environment:
          MAVEN_CLI_OPTS: "-s settings.xml"
          MAVEN_OPTS: "-Dmaven.repo.local=maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

    steps:
      - checkout
      - run:
          name: Print mvn version
          command: mvn -version
      - run:
          name: mvn clean
          command: mvn ${MAVEN_CLI_OPTS} clean